FROM openjdk:17.0.1-jdk-slim
ARG JAR_FILE=build/libs/dga-0.0.1-SNAPSHOT.war
    
COPY ${JAR_FILE} ./DgaBoard.war

ARG PSQL_HOST \
    PSQL_PORT \
    PSQL_USERNAME \
    PSQL_PASSWORD \
    BOARD_ACCESS_KEY \
    BOARD_SECRET_KEY \
    MONGO_USERNAME \
    MONGO_PASSWORD \
    MONGO_PORT \
    MONGO_HOST
    
ENV PSQL_HOST=${PSQL_HOST} \
    PSQL_PORT=${PSQL_PORT} \
    PSQL_USERNAME=${PSQL_USERNAME} \
    PSQL_PASSWORD=${PSQL_PASSWORD} \
    BOARD_ACCESS_KEY=${BOARD_ACCESS_KEY} \
    BOARD_SECRET_KEY=${BOARD_SECRET_KEY} \
    MONGO_USERNAME=${MONGO_USERNAME} \
    MONGO_PASSWORD=${MONGO_PASSWORD} \
    MONGO_PORT=${MONGO_PORT} \
    MONGO_HOST=${MONGO_HOST}
    
    
ENTRYPOINT ["java","-jar", "./DgaBoard.war"]
