spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PSQL_HOST}:${PSQL_PORT}/${PSQL_DATABASE}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        # 개발시 로그
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: true
        generate-ddl: true
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: '8085'

# 운영시 로그
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
# AWS
cloud:
  aws:
    s3:
      bucket: daddygoimageupload #버킷이름
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${BOARD_ACCESS_KEY}
      secretKey: ${BOARD_SECRET_KEY}