spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin1
  jpa:

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # 개발시 로그
        show-sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: '8085'

# 운영시 로그
logging:
  level:
    org.hibernate.sql: debug