spring:
  config:
    import:
      - classpath:/aws.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        # 개발시 로그
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: true
        generate-ddl: true
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: '8085'

#cloud:
#  aws:
#    credentials:
#      instanceProfile: true

      # cloud.aws.credentials.accessKey
      # cloud.aws.credentials.secretKey

# 운영시 로그
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace